add Testcontainers.Consul
testcontainers/testcontainers-dotnet pull request #1028
Opened 2023-10-16 13:38 UTC by witskeeper

## What does this PR do?

add Testcontainers.Consul

## Why is it important?

support consul containers

2023-10-17 17:14 UTC, HofmeisterAn requested changes
Thank you for your contribution and the pull request. Overall, it looks good. I do have a few minor suggestions and changes that we need to address before we can merge it. Thanks again.

2023-10-17 17:14 UTC, HofmeisterAn commented on Testcontainers.sln
>  EndProject
Please remove the unnecessary changes from the Solution file.

2023-10-17 17:14 UTC, HofmeisterAn commented on src/Testcontainers.Consul/ConsulBuilder.cs
> +            .WithWaitStrategy(Wait.ForUnixContainer().AddCustomWaitStrategy(new WaitUntil()));
Please use the HTTP [wait strategy](https://dotnet.testcontainers.org/api/wait_strategies/#waiting-for-http-response-status-code-200-ok-on-port-80). Java checks the [/v1/status/leader](https://github.com/testcontainers/testcontainers-java/blob/57ca6ad4f0a6ee8bb5feaf428b5c66c7d25259c4/modules/consul/src/main/java/org/testcontainers/consul/ConsulContainer.java#L49) endpoint to detect readiness. I am not sure which one is prefered. Does the health API reliably indicate readiness?

Java sets a few [additional](https://github.com/testcontainers/testcontainers-java/blob/57ca6ad4f0a6ee8bb5feaf428b5c66c7d25259c4/modules/consul/src/main/java/org/testcontainers/consul/ConsulContainer.java#L51-L53) configurations too. It would be great if we could adjust our configuration with Java's.

2023-10-17 17:14 UTC, HofmeisterAn commented on tests/Testcontainers.Consul.Tests/ConsulContainerTest.cs
> +    private readonly ConsulContainer _ConsulContainer = new ConsulBuilder().Build();
```suggestion
    private readonly ConsulContainer _consulContainer = new ConsulBuilder().Build();
```

2023-10-17 17:14 UTC, HofmeisterAn commented on src/Testcontainers.Consul/ConsulContainer.cs
> +        return new UriBuilder("http", Hostname, GetMappedPublicPort(ConsulBuilder.ConsulPort)).Uri.Authority;
```suggestion
        return new UriBuilder(Uri.UriSchemeHttp, Hostname, GetMappedPublicPort(ConsulBuilder.ConsulPort)).ToString();
```

Then you can simply use the connection string in the test (you do not need to prepend `http://`).

2023-10-19 17:10 UTC, HofmeisterAn commented
Thank you for addressing the suggestions. I have briefly reviewed the PR, and it looks good. I plan to merge it either tomorrow or the day after, depending on my availability.

2023-10-20 13:01 UTC, witskeeper commented
glad to be able to contribute code.

2023-10-21 17:27 UTC, merged