Update Azurite to 3.28.0 and add support for --inMemoryPersistence
testcontainers/testcontainers-dotnet pull request #1063
Opened 2023-12-01 19:49 UTC by Xzelsius

## What does this PR do?

Updates the default Azurite image to v3.28.0
Additionally, adds support for the new in-memory persistence flag `--inMemoryPersistence`

The new in-memory persistence is opt-in and needs to be enabled using `.WithInMemoryPersistence()` on the Azurite builder.
As default, the memory limit is 50% of the available Docker host RAM, but it can be overridden by specifying it in the `.WithInMemoryPersistence(<memory-limit-in-mb>)` call.

## Why is it important?

Using in-memory persistence may have a positive effect on overall performance of Azurite during tests, as it does not need to store stuff on disk.

## Related issues

- Closes #1060

2023-12-02 09:29 UTC, HofmeisterAn requested changes
Thanks for the PR 👍 I have some minor change requests, but overall, it looks really good. I will be happy to merge it once the requested changes are addressed.

2023-12-02 09:29 UTC, HofmeisterAn commented on src/Testcontainers.Azurite/AzuriteBuilder.cs
> +        };
Can we please move this part to the builder `Init()` method?

```csharp
.WithEntrypoint("azurite")
.WithCommand("--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0");
```

2023-12-02 09:29 UTC, HofmeisterAn commented on src/Testcontainers.Azurite/AzuriteBuilder.cs
> +            .WithCommand(command.ToArray());
Then we can replace this lines with:

```csharp
if (memoryLimit.HasValue)
{
    return WithCommand("--inMemoryPersistence", "--extentMemoryLimit", memoryLimit.ToString());
}
else
{
    return WithCommand("--inMemoryPersistence");
}
```

2023-12-02 09:29 UTC, HofmeisterAn commented on src/Testcontainers.Azurite/AzuriteBuilder.cs
> +
I do not expect we need this wait strategy. I expect Azurite to be ready when the services are available.

2023-12-02 09:29 UTC, HofmeisterAn commented on src/Testcontainers.Azurite/AzuriteConfiguration.cs
> +    public AzuriteConfiguration(bool inMemoryPersistence = false, int? extentMemoryLimit = null)
I do not think we need to keep the values. As long as we do not need them later (e.g. in the container instance) it is not necessary to keep them in the configuration instance. At least that's how we do it in other modules.

2023-12-05 17:01 UTC, HofmeisterAn commented
I made slight changes to the tests. Instead of creating a new class, we can reuse the previous test class. Does the PR look good to you? What do you think? I am ready to merge it. Thanks for your contribution.

2023-12-05 21:09 UTC, Xzelsius commented
@HofmeisterAn That's actually a way better solution than what I did with the test :)
Looks good to me 👍

2023-12-06 16:52 UTC, HofmeisterAn approved these changes, later dismissed
Thanks for creating the issue and PR 🙏.

2023-12-06 18:37 UTC, merged