Provide deterministic builds with SourceLink support
testcontainers/testcontainers-dotnet pull request #1129
Opened 2024-02-24 13:46 UTC by tom-englert

## What does this PR do?

Add SourceLink package to provide deterministic builds

## Why is it important?

Provide "state of the art" debugging experience

## Related issues

- Closes #1128

2024-02-24 14:27 UTC, HofmeisterAn reviewed
According to this [comment](https://github.com/testcontainers/testcontainers-dotnet/pull/1054#issuecomment-1828082264) and this [section](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects), Source Link is now included in the SDK. The added properties, among others, are set in our Cake build [file](https://github.com/testcontainers/testcontainers-dotnet/blob/8aee376aa98018d07d270264920161113dfd8490/build.cake#L138). According to the Source Link docs, they are not necessary anymore, either. Probably, we can even remove them.

Is something not working? Had havent had issues in the past debugging the library.

2024-02-24 15:06 UTC, tom-englert commented
It should look like this:
- no symbol server
- deterministic, including repo ulr & commit
![image](https://github.com/testcontainers/testcontainers-dotnet/assets/10229954/50515162-2f7e-4364-b22b-730da44c6854)

I'll have a look whats wrong with this...

2024-02-24 15:13 UTC, HofmeisterAn commented
> It should look like this:

I see, thanks! Maybe we just need to move the properties (args) to the Cake build task (the pack task does not rebuild the projects):

```diff
diff --git a/build.cake b/build.cake
index 1d2e4ae..0843d4e 100644
--- a/build.cake
+++ b/build.cake
@@ -67,6 +67,8 @@ Task("Build")
     Verbosity = param.Verbosity,
     NoRestore = true,
     ArgumentCustomization = args => args
+      .Append("/p:ContinuousIntegrationBuild=true")
+      .Append("/p:EmbedUntrackedSources=true")
   });
 });
 
@@ -134,8 +136,6 @@ Task("Create-NuGet-Packages")
     SymbolPackageFormat = "snupkg",
     OutputDirectory = param.Paths.Directories.NuGetDirectoryPath,
     ArgumentCustomization = args => args
-      .Append("/p:ContinuousIntegrationBuild=true")
-      .Append("/p:EmbedUntrackedSources=true")
       .Append($"/p:Version={param.Version}")
   });
 });
```

2024-02-24 15:22 UTC, tom-englert commented
Probably yes, and the symbols should be embedded rather than having a separate symbol package, from my experience the latter never works without friction.

2024-02-24 15:25 UTC, tom-englert commented
But maybe .Append("/p:ContinuousIntegrationBuild=true") should not really be needed, SourceLink should determine this automatically

2024-02-24 15:52 UTC, tom-englert commented
https://github.com/dotnet/sourcelink/blob/a22426a46745b8fe77b9d306fa4bc1d03eff44ea/src/Microsoft.Build.StandardCI/build/Microsoft.Build.StandardCI.props#L15-L19

2024-02-24 16:19 UTC, tom-englert commented
This is what I got with the current version of TestContainers:
- listed in the "External Sources", but seems not to match the symbols found on the symbol server.
![image](https://github.com/testcontainers/testcontainers-dotnet/assets/10229954/ce117372-94ba-4e2c-b498-39830126e0c2)

2024-02-24 16:32 UTC, HofmeisterAn requested changes
> This is what I got with the current version of TestContainers:

This is strange. Sorry, I do not have access to Visual Studio. Rider seems to be able to download the symbols, etc. I can debug into the sources without any issues. However, we can merge the suggestions. The NuGet Package Explorer looks even better with them. Thanks.

2024-02-24 16:32 UTC, HofmeisterAn commented on Directory.Build.props
> +    <EmbedUntrackedSources>true</EmbedUntrackedSources>
```suggestion
```

I did some local tests, and it appears that this property is indeed not necessary.

2024-02-24 16:32 UTC, HofmeisterAn commented on build.cake
> +    IncludeSymbols = false,
```suggestion
```

Its default value is `false`.

2024-02-24 16:32 UTC, HofmeisterAn commented on build.cake
> +  foreach(var package in GetFiles($"{param.Paths.Directories.NuGetDirectoryPath}/*.nupkg"))
```suggestion
  foreach (var package in GetFiles($"{param.Paths.Directories.NuGetDirectoryPath}/*.nupkg"))
```

2024-02-24 17:13 UTC, HofmeisterAn commented
I published the pipeline artifacts (NuGets) to ensure that the NuGets are built and configured properly, and everything is set up correctly for the next release. It appears that `ContinuousIntegrationBuild` is somehow not automatically applied to the build. We need to set it explicitly ([before](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/8031926977) and [after](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/8031957625)).

![image](https://github.com/testcontainers/testcontainers-dotnet/assets/9199345/86702ca1-ca21-44c5-aeb7-47ac5f3cdcf9)

2024-02-24 17:25 UTC, tom-englert commented
Strange, I never had to set this - however I never used Cake, maybe that's special about this.

2024-02-24 18:11 UTC, HofmeisterAn commented
Probably, we cannot enable `ContinuousIntegrationBuild` that easily 😐. It obviously breaks our [CommonDirectoryPathTest](https://github.com/testcontainers/testcontainers-dotnet/runs/21941308921#r44s1) tests. Not sure how (or if) we can solve this, because we are using the `CallerFilePath` attribute to resolve common directory paths:

https://github.com/testcontainers/testcontainers-dotnet/blob/5c677d9ac043d414ecc3c165c265700c98668808/src/Testcontainers/Builders/CommonDirectoryPath.cs#L61-L65

2024-02-25 07:18 UTC, tom-englert commented
> It obviously breaks our [CommonDirectoryPathTest](https://github.com/testcontainers/testcontainers-dotnet/runs/21941308921#r44s1) tests

That's strange, how can this have such a side effect? And why only on linux?

2024-02-25 08:22 UTC, HofmeisterAn commented
> > It obviously breaks our [CommonDirectoryPathTest](https://github.com/testcontainers/testcontainers-dotnet/runs/21941308921#r44s1) tests
> 
> That's strange, how can this have such a side effect? And why only on linux?

I think I found the "reason" and have a potential working configuration, which also explains why you never had to set `ContinuousIntegrationBuild` explicitly. I need a few more minutes to validate my changes.

2024-02-25 08:57 UTC, HofmeisterAn commented
If we set `ContinuousIntegrationBuild` to `true` during the build, it will break the tests because `CallerFilePath` now returns a deterministic root path. We can simply disable `ContinuousIntegrationBuild` for the test projects. 

My [assumption](https://github.com/testcontainers/testcontainers-dotnet/commit/e6f1746956e165c1a7e569d55a17b63c833ed46d) was, if we allow Cake to rebuild the packages on `Pack` (if the packages are already built, we likely need to force a rebuild), the `ContinuousIntegrationBuild` is applied automatically, and it won't interfere with the tests. Unfortunately, the configuration is not applied automatically...

2024-02-25 12:34 UTC, HofmeisterAn commented
I do not think we need that many changes. The following [changes](https://github.com/tom-englert/testcontainers-dotnet/compare/%231128...testcontainers:testcontainers-dotnet:feature/tom-englert-%231128) work [fine](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/8037822226) (incl. Sonar). We just need to make sure the pack target rebuilds the NuGets. I am still wondering why we need to set `ContinuousIntegrationBuild` explicitly, but maybe Source Link behaves differently if the source control provider is added explicitly.

![image](https://github.com/testcontainers/testcontainers-dotnet/assets/9199345/7dd6869b-4652-4709-9d66-10411935a192)

2024-02-25 13:20 UTC, tom-englert commented
Just needed to turn off deterministic for the tests, they don't get deployed anyhow.

2024-02-26 06:38 UTC, HofmeisterAn commented on src/Testcontainers/Builders/CommonDirectoryPath.cs
>      }
Can we please revert these changes and only include changes that are necessary to embed the symbols / enable deterministic paths?

2024-02-26 06:38 UTC, HofmeisterAn commented on tests/Testcontainers.Tests/Testcontainers.Tests.csproj
> +  </PropertyGroup>
Can we please move this to `tests/Directory.Build.props` so that the properties apply to the other test projects too?

2024-02-26 06:55 UTC, tom-englert commented on tests/Testcontainers.Tests/Testcontainers.Tests.csproj
> +  </PropertyGroup>
Sure, just wasn't aware that this already exists.

2024-02-26 07:12 UTC, HofmeisterAn approved these changes
Thank you for the efforts, and apologies for the back and forth.

2024-02-26 07:15 UTC, merged

2024-02-26 11:47 UTC, tom-englert commented
Happy to contribute to such a great tool! Thanks for all YOUR efforts 😄