Add Keycloak health port 9000 starting with tag 25.0
testcontainers/testcontainers-dotnet pull request #1213
Opened 2024-07-15 11:51 UTC by paulomorgado

## What does this PR do?

Starting with tag `25.0` Keycloak uses port 9000 instead of port 8080 for health checks.

## Why is it important?

Currently the readiness for image `25.0` and above is not correct and might consider the container ready when it's yet ready.

## Related issues

- Closes #1208

## How to test this PR

Use tag 24.0 and tag 25.0 and asset that all correctly wait for the container to be ready.

2024-07-17 09:34 UTC, HofmeisterAn commented
For reference, it looks like the changes were introduced in version 25, according to the [release notes](https://www.keycloak.org/docs/latest/release_notes/index.html#management-port-for-metrics-and-health-endpoints).

2024-07-31 18:01 UTC, HofmeisterAn requested changes
Sorry it took me so long to review. Thank you for taking the time to contribute, create a PR, and fix the issue. I have a few small change requests. What do you think? Thanks again.

2024-07-31 18:01 UTC, HofmeisterAn commented on src/Testcontainers.Keycloak/KeycloakBuilder.cs
> +        return new KeycloakContainer(builder.DockerResourceConfiguration);
```suggestion
        Validate();

        var majorVersionString = new string(DockerResourceConfiguration.Image.Tag.TakeWhile(char.IsDigit).ToArray());

        var isLatestVersion = "latest".Equals(DockerResourceConfiguration.Image.Tag, StringComparison.OrdinalIgnoreCase);

        // https://www.keycloak.org/docs/latest/release_notes/index.html#management-port-for-metrics-and-health-endpoints.
        var isMajorVersionAtLeast25 = int.TryParse(majorVersionString, out var majorVersion) && majorVersion >= 25;

        var waitStrategy = Wait.ForUnixContainer()
            .UntilHttpRequestIsSucceeded(request =>
                request.ForPath("/health/ready").ForPort(isLatestVersion || isMajorVersionAtLeast25 ? KeycloakHealthPort : KeycloakPort));

        var couchbaseBuilder = DockerResourceConfiguration.WaitStrategies.Count() > 1 ? this : WithWaitStrategy(waitStrategy);
        return new KeycloakContainer(couchbaseBuilder.DockerResourceConfiguration);
```

We need to check the `latest` tag as well. In addition, the tag does not necessarily require a dot separator. I am not sure if this is the case for the Keycloak images too, but sometimes tags for images are like: 25, 25.1, 25.1.3, etc. This requires updating the global usings as well (add LINQ).

In addition we can remove the wait strategy configuration from `Init()`.

2024-07-31 18:01 UTC, HofmeisterAn commented on tests/Testcontainers.Keycloak.Tests/KeycloakContainerHealthTest.cs
> +    [InlineData("quay.io/keycloak/keycloak:25.0")]
In case we need to run the same tests against different configurations (versions), we usually use the following pattern (this allows us to run the tests and download the images in parallel). For example, this is from [Mongo DB](https://github.com/testcontainers/testcontainers-dotnet/blob/21137c61fb36774b0aee16304e1587fa0f662673/tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs#L52-L86). Would you mind if we change the test to follow the same pattern?

2024-07-31 19:12 UTC, paulomorgado commented on tests/Testcontainers.Keycloak.Tests/KeycloakContainerHealthTest.cs
> +    [InlineData("quay.io/keycloak/keycloak:25.0")]
I don't understand what's being asked here.

But, if you guide me, I'm sure I can do it.

I don't use JetBrains products.

2024-08-07 17:19 UTC, HofmeisterAn approved these changes

2024-08-07 17:20 UTC, merged

2024-08-07 17:20 UTC, HofmeisterAn commented
Thanks @paulomorgado 🙏.