Add Db2 module
testcontainers/testcontainers-dotnet pull request #1237
Opened 2024-08-20 08:58 UTC by kevin0x90

## What does this PR do?

Adds a module to use Db2 with testcontainers.

## How to test this PR

Automated tests have been added to the project that verify startup and database connectivity.

2024-09-03 19:40 UTC, kevin0x90 commented
TODO: use code includes like

```
<!--codeinclude-->
[Usage Example](../../tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs) inside_block:UseElasticsearchContainer
<!--/codeinclude-->
```

in documentation

2025-01-27 19:53 UTC, HofmeisterAn requested changes
Thank you for the PR and your contribution! I apologize for the delayed review and feedback. I just hadn't found the time earlier. I have a few minor change requests (or questions), but nothing major. I'm happy to merge the PR once those are addressed 🙏.

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +        .WithLicenseAgreement()
Can we please use the same pattern as we do in the ServiceBus module: [1)](https://github.com/testcontainers/testcontainers-dotnet/blob/888da44936457c0d3dea0d149e4fb61f23544b33/src/Testcontainers.ServiceBus/ServiceBusBuilder.cs#L43-L55), [2)](https://github.com/testcontainers/testcontainers-dotnet/blob/888da44936457c0d3dea0d149e4fb61f23544b33/src/Testcontainers.ServiceBus/ServiceBusBuilder.cs#L64-L76)?

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +    }
Do we need to provide an API for these configurations? Usually, modules only include what's necessary to run the container; we do not provide an API for every single configuration. Developers can always configure the environment variables themselves (if they are optional).

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +        .WithPrivileged(true);
Does it need to run in privileged mode?

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +        return Merge(DockerResourceConfiguration, new Db2Configuration(licenseAgreement: DefaultInMemoryDatabasePath))
This line passes the value to the wrong argument.

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Configuration.cs
> +    public string InMemoryDatabasePath { get; }
We only include the properties in the configuration type that we will need later in the container type.

2025-01-27 19:53 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +    public const string Db2Image = "icr.io/db2_community/db2:latest";
Please pin the version.

2025-01-27 19:53 UTC, HofmeisterAn commented on tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.targets
> +        />
I moved these parts to a separate targets file. Can't we set the values directly in the `runsettings` file? (I'm not sure if the actual base path is `$(MSBuildProjectDirectory)/$(OutputPath)` already; and we can simply use the relative path).

2025-01-27 19:59 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +            );
Please move the wait strategy configuration to `Init()`. We do not need the pattern here. We only need it if we need to configure the wait strategy with developer-provided configurations.

2025-01-27 20:02 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +        .WithLicenseAgreement()
Will adjust

2025-01-27 20:03 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +    }
I thought it makes these settings more discoverable for users.

2025-01-27 20:06 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +        .WithPrivileged(true);
Sadly yes according to the documentation
https://www.ibm.com/docs/en/db2/12.1?topic=system-linux

2025-01-27 20:06 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +        return Merge(DockerResourceConfiguration, new Db2Configuration(licenseAgreement: DefaultInMemoryDatabasePath))
Will adjust

2025-01-27 20:07 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +    public const string Db2Image = "icr.io/db2_community/db2:latest";
Will adjust

2025-01-27 20:10 UTC, kevin0x90 commented on tests/Testcontainers.Db2.Tests/Testcontainers.Db2.Tests.targets
> +        />
I’m also not sure but to me it looked like the environment variables need to have an absolute path that’s why I implemented it in this way in order to use variables from MSBuild for the absolute path construction.

2025-02-01 19:12 UTC, HofmeisterAn commented on src/Testcontainers.Db2/Db2Builder.cs
> +    }
From our experience providing APIs (except when necessary to start the container), for configurations that can simply be set through environment variables have several disadvantages:

- Depending on the number of configurations, providing APIs for all of them requires significant effort.
- Distinguishing between different image versions and their respective configurations is difficult.
- We need to include and maintain documentation.
- Keeping the APIs and documentations up to date.

Testcontainers' modules are opinionated, pre-configured, and follow best practice configurations. A module does not need to support all possible use cases. If developers require a specific configuration, they can always use the generic builder (`ContainerBuilder()`).

If certain configurations are useful for development and testing, we should set them by default, as we do for [PostgreSQL](https://github.com/testcontainers/testcontainers-dotnet/blob/2c6c915e84f03d239a94e26b81f867f03f6a0942/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs#L92-L95). If the APIs are not necessary, I recommend removing them.

2025-02-10 21:37 UTC, kevin0x90 commented on src/Testcontainers.Db2/Db2Builder.cs
> +        .WithLicenseAgreement()
I have just seen that I also have to adjust this part. Will fix it in the next few days.

2025-02-13 14:42 UTC, HofmeisterAn reviewed
Thanks for updating the PR. I've updated the remaining parts. The PR looks good! If you're okay with it, I'm happy to merge it.

I just have one final question: Does it make sense to set any of these configurations as defaults (in `Init()`) to improve startup performance?

```csharp
.WithEnvironment("TO_CREATE_SAMPLEDB", "false")
.WithEnvironment("PERSISTENT_HOME", "true")
.WithEnvironment("REPODB", "false")
.WithEnvironment("BLU", "false")
.WithEnvironment("HADR_ENABLED", "false")
.WithEnvironment("ARCHIVE_LOGS", "false")
.WithEnvironment("AUTOCONFIG", "false")
```

2025-02-13 14:42 UTC, HofmeisterAn commented on Testcontainers.sln
>  	EndGlobalSection
```suggestion
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
```

2025-02-14 16:29 UTC, HofmeisterAn approved these changes

2025-02-14 16:30 UTC, merged

2025-02-15 21:09 UTC, kevin0x90 commented
> Thanks for updating the PR. I've updated the remaining parts. The PR looks good! If you're okay with it, I'm happy to merge it.
> 
> I just have one final question: Does it make sense to set any of these configurations as defaults (in `Init()`) to improve startup performance (or improves development experience)?
> 
> ```cs
> .WithEnvironment("TO_CREATE_SAMPLEDB", "false")
> .WithEnvironment("PERSISTENT_HOME", "true")
> .WithEnvironment("REPODB", "false")
> .WithEnvironment("BLU", "false")
> .WithEnvironment("HADR_ENABLED", "false")
> .WithEnvironment("ARCHIVE_LOGS", "false")
> .WithEnvironment("AUTOCONFIG", "false")
> ```

Thank you very much for finishing up the PR for the parts I had not addressed yet.