Issue 1291
testcontainers/testcontainers-dotnet pull request #1294
Opened 2024-11-09 12:15 UTC by keshramjith

## What does this PR do?

- Upgraded the default Apache Pulsar docker image to 4.0 LTS
- Changed user to root, to create secret.key for auth
- Fixed script

## Why is it important?

## Related issues

-

2024-11-13 20:13 UTC, HofmeisterAn requested changes

2024-11-13 20:13 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +    public const string PulsarImage = "apachepulsar/pulsar:4.0.0";
```suggestion
    public const string PulsarImage = "apachepulsar/pulsar:3.0.6";
```

As mentioned in the issue, we don't update the image version unless it is absolutely necessary. We try to maintain backward compatibility.

2024-11-13 20:13 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +            .WithCreateParameterModifier(parameterModifier => parameterModifier.User = "root")
If this issue is just about permission problems, can't we store the key somewhere else? For example, `SecretKeyFilePath = "/pulsar/data/.pulsar/secret.key"` should work. This makes the change in `PulsarContainer` unnecessary too.

2025-01-25 10:02 UTC, rafek1241 commented
Lack of documentation update if you change the docker version (docs/modules/index.md)

2025-01-31 14:48 UTC, closed without merging