[#258] #IMPLEMENT 'assemblyName: DotNet.Testcontainers; function: CouchbaseTestcontainer' {Add pre-configured Couchbase Testcontainer.}
testcontainers/testcontainers-dotnet pull request #296
Opened 2020-07-20 21:53 UTC by mustafaonuraydin

[#258] #IMPLEMENT 'assemblyName: DotNet.Testcontainers; function: CouchbaseTestcontainer' {Add pre-configured Couchbase Testcontainer.}

2020-07-20 22:14 UTC, mustafaonuraydin commented
@HofmeisterAn I create new pull request with new branch. I tried to refactor and improve with you suggestion. Additionally, i updated latest version of Couchbase.
You can see customized docker image source from following repository;
https://github.com/mustafaonuraydin/couchbase-docker-image-for-testcontainers

After your review please feel free to ask for other changes or ideas and i really appreciate to discuss over code.

2020-07-21 12:24 UTC, HofmeisterAn requested changes
LGTM 👍 It would be nice if you could add the suggested comment below. Then I'll merge it later that day.

2020-07-21 12:24 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Containers/Configurations/Databases/CouchbaseTestcontainerConfiguration.cs
> +    private const string CouchbaseImage = "mustafaonuraydin/couchbase-testcontainer:6.5.1";
Maybe you can add some information (comment) about the image here until the sources are public.

2020-07-21 14:42 UTC, mustafaonuraydin commented on src/DotNet.Testcontainers/Containers/Configurations/Databases/CouchbaseTestcontainerConfiguration.cs
> +    private const string CouchbaseImage = "mustafaonuraydin/couchbase-testcontainer:6.5.1";
Coming 👍

2020-07-21 14:49 UTC, mustafaonuraydin commented
@HofmeisterAn i sent updates with your suggestion. Thanks for your support! I hope this feature will helpful to community. 🎉

2020-07-21 17:04 UTC, HofmeisterAn approved these changes

2020-07-21 19:42 UTC, HofmeisterAn commented
Merged with 2cc3c6e398f9e6b068f0f4a306888fd251502a70 and c78c30bf940d9a8812c5c128ab89f777040b0974.

2020-07-21 19:42 UTC, closed without merging