6688 – UDP port exposing and binding
testcontainers/testcontainers-dotnet pull request #368
Opened 2021-03-01 17:10 UTC by Uzivatel919

• support for UDP ports bindings and exposing

2021-03-01 18:03 UTC, HofmeisterAn requested changes
Thanks for your pull request! Could you please add a unit test (UDP binding) and consider the commit message [guideline](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/CONTRIBUTING.md#commit-messages).

2021-03-01 18:03 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Internals/Mappers/TestcontainersConfigurationConverter.cs
> +    private const string
- Please put `const` at the top of the class.
- Please do not assign multiple variables at once.
- Maybe use `UdpPrefix` and `TcpPrefix` (I don't know if `Denoter` even exists).

2021-03-01 18:03 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Internals/Mappers/TestcontainersConfigurationConverter.cs
> +    private static string GetQualifiedPort(string val) => val.EndsWith(TcpDenoter) || val.EndsWith(UdpDenoter) ? val : $"{val}{TcpDenoter}";
- To statement body please.
- Use `containerPort` instead of `val`.
- Use `EndsWith(..., StringComparison.OrdinalIgnoreCase)`.

2021-03-01 18:06 UTC, Uzivatel919 commented
> Thanks for your pull request! Could you please add a unit test (UDP binding) and consider the commit message [guideline](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/CONTRIBUTING.md#commit-messages).

Sure.

2021-03-06 12:05 UTC, Uzivatel919 commented on src/DotNet.Testcontainers/Internals/Mappers/TestcontainersConfigurationConverter.cs
> +    private static string GetQualifiedPort(string val) => val.EndsWith(TcpDenoter) || val.EndsWith(UdpDenoter) ? val : $"{val}{TcpDenoter}";
Done.

2021-03-06 12:06 UTC, Uzivatel919 commented on src/DotNet.Testcontainers/Internals/Mappers/TestcontainersConfigurationConverter.cs
> +    private const string
Done.

2021-03-06 14:10 UTC, HofmeisterAn commented
I'll rebase, squash and merge it later. Thanks.

2021-03-06 16:26 UTC, HofmeisterAn approved these changes

2021-03-06 16:30 UTC, HofmeisterAn commented
Merged with #371.

2021-03-06 16:30 UTC, closed without merging