Add exec function that returns the stdout and stderr of the container
testcontainers/testcontainers-dotnet pull request #392
Opened 2021-08-19 01:56 UTC by fabiogouw

This PR address the issue #390 , I'm taking the approach that creates a new method so no usage is broken. Please let me know if it's ok or if it needs any kind of improvement. Thank you.

2021-08-19 11:29 UTC, HofmeisterAn requested changes
PR looks good! Thanks. I suggest only a few small changes. If you don't mind, I think we should use the existing `ExecAsync` method. Even it is a breaking change, I think it's better to stay close to the Java implementation. Version 1.6 has breaking changes anyway (renaming namespaces).

Thanks again.

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs
> +      var stream = await this.Docker.Exec.StartAndAttachContainerExecAsync(created.ID, false, ct);
`.ConfigureAwait(false);`

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/ExecResult.cs
> +namespace DotNet.Testcontainers.Clients
Move the file to `src\DotNet.Testcontainers\Containers\`, namespace `DotNet.Testcontainers.Containers`.

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/ExecResult.cs
> +  public class ExecResult
Please use constructor initialization.

```cs
public readonly struct ExecResult
{
  public ExecResult(string stdOut, string stdErr, long exitCode)
  {
    this.StdOut = stdOut;
    this.StdErr = stdErr;
    this.ExitCode = exitCode;
  }

  public string StdOut { get; }

  public string StdErr { get; }

  public long ExitCode { get; }
}
```

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs
> +          break;
`return new ExecResult(stdOut, stdErr, response.ExitCode);` see `ExecResult` suggestions.

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs
> +      return results;
`return new ExecResult(string.Empty, string.Empty, long.MinValue)`.

2021-08-19 11:29 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs
> +          (results.StdOut, results.StdErr) = await stream.ReadOutputToEndAsync(ct);
`.ConfigureAwait(false);`

2021-08-19 16:31 UTC, fabiogouw commented on src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs
> +      var stream = await this.Docker.Exec.StartAndAttachContainerExecAsync(created.ID, false, ct);
Done!

2021-08-19 16:37 UTC, fabiogouw commented
Thanks for your considerations, @HofmeisterAn , I made all the changes. However, the pipeline now hangs in the Tests stage, I'll take a look at the root cause.

2021-08-19 18:47 UTC, HofmeisterAn commented
> Thanks for your considerations, @HofmeisterAn , I made all the changes. However, the pipeline now hangs in the Tests stage, I'll take a look at the root cause.

It's because the wait strategies never return, see:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Configurations/WaitStrategies/UntilUnixCommandIsCompleted.cs#L29

We need to double check the `ExecAsync` calles. I'll take a look at it tomorrow, but I'm pretty sure there are not many left.

2021-08-19 23:56 UTC, fabiogouw commented
> > Thanks for your considerations, @HofmeisterAn , I made all the changes. However, the pipeline now hangs in the Tests stage, I'll take a look at the root cause.
> 
> It's because the wait strategies never return, see:
> 
> https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Configurations/WaitStrategies/UntilUnixCommandIsCompleted.cs#L29
> 
> We need to double check the `ExecAsync` calles. I'll take a look at it tomorrow, but I'm pretty sure there are not many left.

Great, that was the problem! Thanks

2021-08-21 05:55 UTC, HofmeisterAn approved these changes

2021-08-21 06:00 UTC, merged