WIP [#399] #IMPLEMENT Helper methods for database script execution
testcontainers/testcontainers-dotnet pull request #401
Opened 2021-09-30 16:20 UTC by fabiogouw

Methods to run scripts against databases:

- SQL scripts for MS SQL, MySQL, Oracle, Postgre;
- Lua scripts for Redis; 
- N1QL scripts for Couchbase

2021-10-07 05:31 UTC, HofmeisterAn commented
I'll do the review in the next days. Did you check the test issue `ShouldExecuteCommandsWhenScriptExecuted`?

2021-10-07 11:16 UTC, fabiogouw commented
I'm still working on it, Andre, trying to figure it out.

2021-10-08 02:33 UTC, fabiogouw commented
> I'm still working on it, Andre, trying to figure it out.

I guess it's ok now!

2021-10-10 06:01 UTC, HofmeisterAn commented
> I guess it's ok now!

👍  I'll do the review end of next week. Unfortunately, I'm not able to do it earlier. Thanks.

2021-10-18 16:35 UTC, HofmeisterAn requested changes
Shouldn't we add the interface `IScriptExecution` to the base class `TestcontainerDatabase`? If the module does not support database scripts (or it has no implementation yet) we can simply throw `NotImplementedException`.

I suggest something like this:

```cs
// TestcontainerDatabase.cs

public abstract class TestcontainerDatabase : HostedServiceContainer, IDatabaseScript
{
  protected TestcontainerDatabase(ITestcontainersConfiguration configuration, ILogger logger)
    : base(configuration, logger)
  {
  }

  // ...

  public virtual string GetTempScriptFile()
  {
    return Path.Combine("/tmp", Guid.NewGuid().ToString("N"), ".tmp");
  }

  public virtual Task<ExecResult> ExecScriptAsync(string script)
  {
    throw new NotImplementedException();
  }
}
```

Then each supported module can override `ExecScriptAsync`, e. g.:

```cs
// PostgreSqlTestcontainer.cs

public override async Task<ExecResult> ExecScriptAsync(string script)
{
  var tempScriptFile = this.GetTempScriptFile();

  await this.CopyFileAsync(tempScriptFile, Encoding.UTF8.GetBytes(script))
    .ConfigureAwait(false);

  return await this.ExecAsync(new[] { "psql", "-U", this.Username, "-d", this.Database, "-a", "-f", tempScriptFile })
    .ConfigureAwait(false);
}
```

Everything else looks good 👍 . Thanks for the pull request and contribution.

2021-10-18 16:35 UTC, HofmeisterAn commented on tests/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CouchbaseTestcontainerTest.cs
> +    public async Task ShouldExecuteCommandsWhenScriptExecuted()
A consistent test method name (for all script tests) would be nice. What about something like `ExecScriptInRunningContainer`?

2021-10-18 16:35 UTC, HofmeisterAn commented on tests/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/CouchbaseTestcontainerTest.cs
> +      var script = @"
Please use `const string script` instead of `var script`, other tests too.

2021-10-18 16:35 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Containers/Modules/IScriptExecution.cs
> +  public interface IScriptExecution
What about `IDatabaseScript`?

2021-10-18 16:35 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Containers/Modules/IScriptExecution.cs
> +    Task<ExecResult> ExecScript(string scriptContent);
`ExecScriptAsync`

2021-10-18 16:35 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Containers/Modules/IScriptExecution.cs
> +    /// Executes a script in the database container.
`Executes a database script in the running Testcontainer.`

2021-10-22 20:47 UTC, fabiogouw commented
> Shouldn't we add the interface `IScriptExecution` to the base class `TestcontainerDatabase`? If the module does not support database scripts (or it has no implementation yet) we can simply throw `NotImplementedException`.
> 
> I suggest something like this:
> 
> ```cs
> // TestcontainerDatabase.cs
> 
> public abstract class TestcontainerDatabase : HostedServiceContainer, IDatabaseScript
> {
>   protected TestcontainerDatabase(ITestcontainersConfiguration configuration, ILogger logger)
>     : base(configuration, logger)
>   {
>   }
> 
>   // ...
> 
>   public virtual string GetTempScriptFile()
>   {
>     return Path.Combine("/tmp", Guid.NewGuid().ToString("N"), ".tmp");
>   }
> 
>   public virtual Task<ExecResult> ExecScriptAsync(string script)
>   {
>     throw new NotImplementedException();
>   }
> }
> ```
> 
> Then each supported module can override `ExecScriptAsync`, e. g.:
> 
> ```cs
> // PostgreSqlTestcontainer.cs
> 
> public override async Task<ExecResult> ExecScriptAsync(string script)
> {
>   var tempScriptFile = this.GetTempScriptFile();
> 
>   await this.CopyFileAsync(tempScriptFile, Encoding.UTF8.GetBytes(script))
>     .ConfigureAwait(false);
> 
>   return await this.ExecAsync(new[] { "psql", "-U", this.Username, "-d", this.Database, "-a", "-f", tempScriptFile })
>     .ConfigureAwait(false);
> }
> ```
> 
> Everything else looks good 👍 . Thanks for the pull request and contribution.

@HofmeisterAn, thanks for your comments, I changed the code so most of them are implemented now, but there's one I'd like to discuss further.

When I was developing this code, my first thought was to change the abstract class TestcontainerDatabase so it could have the ExecScript method, like your suggestion. But I've found out that not all databases have the scripting capability (in the case, CouchDB). So it was strange to me having the CouchDbTestcontainer class with this method, even throwing the NotImplemented exception, so I decided to implement the IScriptExecution interface (now IDatabaseScript, I changed its name) on just the databases that have this feature (most of them, in fact). I think that if a class implements a given interface, it has to implement the feature.

One alternative to this case, for the databases that doesn't have a native script capability, is to let it run generic bash scripts. At least it would work for CouchDB, since it can be manipulated with http call (curl).

What do you think?

2021-10-24 15:55 UTC, HofmeisterAn reviewed
> One alternative to this case, for the databases that doesn't have a native script capability, is to let it run generic bash scripts. At least it would work for CouchDB, since it can be manipulated with http call (curl).

I thought of that, too. If a database does not have native script capabilities `sh` would be helpful. The modules should be moved into their own dependencies anyway. Then they can provide database specific features much easier. As long as this is not the case I think it's easier to maintain from the base class.

> even throwing the NotImplemented exception

I think it's not that bad. If someone needs the script capability then they can always create a pull request. Modules are very simple right now.

2021-10-25 14:27 UTC, fabiogouw commented
Sounds ok to me! I'll implement the `sh` capability in the base class and move the reference to the IDatabaseScript interface to the base class.

2021-10-25 17:25 UTC, HofmeisterAn approved these changes
👍 Thanks, I'll merge it ~~tomorrow~~.

**Edit**:
Sorry - I can't do it today. Tomorrow, I promise 🤞.

2021-10-27 18:01 UTC, HofmeisterAn commented
`1.6.0-beta.2028`

2021-10-27 18:01 UTC, closed without merging

2022-06-15 01:44 UTC, fabiogouw commented
Hello, @HofmeisterAn ! I've noticed that you released a new version of the lib (1.6.0). Is this PR included?

2022-06-15 04:46 UTC, HofmeisterAn commented
> Hello, @HofmeisterAn ! I've noticed that you released a new version of the lib (1.6.0). Is this PR included?

Yes, it is. I'm sorry — I forgot to add it to the release notes. The issue wasn't assigned to the milestone. I'll update the information later that day.

https://github.com/testcontainers/testcontainers-dotnet/blob/2aeec1e9b88b8580c9914b73bee56583ad005e03/src/DotNet.Testcontainers/Containers/Modules/IDatabaseScript.cs#L19

https://github.com/testcontainers/testcontainers-dotnet/blob/2aeec1e9b88b8580c9914b73bee56583ad005e03/src/DotNet.Testcontainers/Containers/Modules/Databases/MsSqlTestcontainer.cs#L34

2022-06-15 13:41 UTC, fabiogouw commented
Great, thanks!
There's also this PR #392, if you could mention it too, the release notes description will be more complete.