[#NON] #EXTEND Support managed volume mounts
testcontainers/testcontainers-dotnet pull request #402
Opened 2021-10-07 13:06 UTC by alesandrino

This PR contains:

- mount managed volumes into the container
- volume builder to create / remove managed volumes

2021-10-07 15:46 UTC, HofmeisterAn commented
I'll need some time to review it, because I'm busy with another project. Thanks for your pull request and your contribution.

2021-10-17 07:27 UTC, HofmeisterAn requested changes
Thanks for your pull request and your contribution. I'd like to discuss some improvements related to the volume interfaces. I think right now they are a bit confusing. Except that, I only found some minor issues or inconsistencies.

What about something like:

```cs
public readonly struct MountType
{
  public static readonly MountType Bind = new MountType("bind");

  public static readonly MountType Mount = new MountType("mount");

  private MountType(string value)
  {
    // ...
  }
}

public interface IMount
{
  MountType Type { get; }

  AccessMode AccessMode { get; }

  string Source { get; }

  string Target { get; }
}

public class BindMount : IMount
{
  public MountType Type { get; }
    = MountType.Bind;

  public AccessMode AccessMode { get; }
    = AccessMode.ReadOnly;

  public string Source { get; }

  public string Target { get; }
}

public class VolumeMount : IMount
{
  public MountType Type { get; }
    = MountType.Mount;

  public AccessMode AccessMode { get; }
    = AccessMode.ReadOnly;

  public string Source { get; }

  public string Target { get; }
}
```

Then we add `WithBind` and `WithVolume` to the builder pattern and set `WithMount` to obsolete?

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Builders/TestcontainersBuilder.cs
> +      return this.WithMount(source, destination, AccessMode.ReadWrite);
I guess that should be `WithVolumeMount`.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Builders/TestcontainersBuilder.cs
> +      var mounts = new IVolumeMount[] { new VolumeMount(new DockerVolume(source), destination, accessMode) };
Please call the overloaded `WithVolumeMount(IDockerVolume source, string destination, AccessMode accessMode)`.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Builders/TestcontainersBuilder.cs
> +      IEnumerable<IMount> mounts = null,
What about the `WithMount`? You'll lose `HostPath` property of `IBindMount`, due the `IBindMount` changes. I think we should avoid casting and setup a proper interface.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Configurations/Volumes/ITestcontainersVolumeConfiguration.cs
> +  public interface ITestcontainersVolumeConfiguration
`internal`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Configurations/Volumes/TestcontainersVolumeConfiguration.cs
> +  }
Add `IReadOnlyDictionary<string, string> Labels` too. That's how we identify resources from the builder (see `ITestcontainersNetworkConfiguration`, `TestcontainersNetworkConfiguration`).

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/DockerVolume.cs
> +    /// <param name="id">The Docker network id.</param>
No arg `id`.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/DockerVolume.cs
> +    public Task RemoveAsync(bool? force = null, CancellationToken ct = default)
Why nullable? Please replace it with a default value e. g. `false`.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/IDockerVolume.cs
> +    /// <returns>Task that completes when the network has been created.</returns>
`when the volume`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/IDockerVolume.cs
> +    /// <returns>Task that completes when the network has been deleted.</returns>
`when the volume`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/NonExistingDockerVolume.cs
> +  internal sealed class NonExistingDockerVolume : IDockerVolume
`/// <inheritdoc cref="IDockerVolume" />`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/NonExistingDockerVolume.cs
> +    private readonly ITestcontainersVolumeConfiguration configuration;
Linebreak

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/NonExistingDockerVolume.cs
> +    public NonExistingDockerVolume(ITestcontainersVolumeConfiguration configuration, ILogger logger)
Constructor documentation.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/IDockerVolume.cs
> +    Task RemoveAsync(bool? force = null, CancellationToken ct = default);
Use `DeleteAsync` instead of `RemoveAsync` (consistency).

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Volumes/IDockerVolume.cs
> +    /// Removes the volume.
`Deletes the volume.`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/IDockerVolumeOperations.cs
> +  public interface IDockerVolumeOperations
`internal`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/IDockerVolumeOperations.cs
> +    Task RemoveAsync(string name, bool? force = null, CancellationToken ct = default);
`DeleteAsync`

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Clients/IDockerVolumeOperations.cs
> +    Task RemoveAsync(string name, bool? force = null, CancellationToken ct = default);
Remove nullable.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Builders/TestcontainersVolumeBuilder.cs
> +      : this(Apply(endpoint: TestcontainersSettings.OS.DockerApiEndpoint))
Please add the labels too.

2021-10-17 07:27 UTC, HofmeisterAn commented on src/DotNet.Testcontainers/Builders/TestcontainersVolumeBuilder.cs
> +    public ITestcontainersVolumeBuilder WithName(string name)
Please add `WithDockerEndpoint` and `WithLabel` too. I'll refactor that later and move it into a base class. I just would like to make sure that I don't forget it here.

2021-10-18 07:37 UTC, alesandrino commented on src/DotNet.Testcontainers/Clients/IDockerVolumeOperations.cs
> +    Task RemoveAsync(string name, bool? force = null, CancellationToken ct = default);
I must admit that I did not really think very much on why I added the parameter as nullable. Basically I just saw it in the Docker.Dotnet interface and copied it over.
I did now have a look at their code and found that the parameter currently is not used at all. I therefor suggest to remove it completely. It will other wise just confuse.

2021-10-18 07:42 UTC, alesandrino commented on src/DotNet.Testcontainers/Builders/TestcontainersBuilder.cs
> +      return this.WithMount(source, destination, AccessMode.ReadWrite);
Thanks a lot for the review! I very much appreciate the effort.
I tried to apply the changes according to your suggestions. Please contact me if I got you wrong.

2021-10-18 07:45 UTC, alesandrino commented on src/DotNet.Testcontainers/Builders/TestcontainersBuilder.cs
> +      IEnumerable<IMount> mounts = null,
agreed the code is much cleaner now.

2021-10-20 13:46 UTC, HofmeisterAn approved these changes
Can you please squash the commits into a single commit (consider the commit message too). Then I'll merge your pr. Thanks.

2021-10-20 15:46 UTC, alesandrino commented
Done. Sorry, for the noise. I am still relatively new to this.

2021-10-20 18:04 UTC, HofmeisterAn commented
I squashed the last 3 commits into a single one and merged them to develop, deployed version: `1.6.0-beta.2014`.

2021-10-20 18:04 UTC, closed without merging