Throwing exception if image doesn't exist after build
testcontainers/testcontainers-dotnet pull request #501
Opened 2022-07-01 14:58 UTC by michal-korniak

Hi
I noticed that the framework doesn't give any feedback's if image is not created. This leads to errors in the other lines of code:

"Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: testcontainers:1656427318745"}"

2022-07-01 15:37 UTC, HofmeisterAn requested changes

2022-07-01 15:37 UTC, HofmeisterAn commented on src/Testcontainers/Clients/DockerImageOperations.cs
> +        bool isImageCreated = await this.ExistsWithNameAsync(image.FullName, ct).ConfigureAwait(false);
`var`

2022-07-01 15:37 UTC, HofmeisterAn commented on src/Testcontainers/Clients/DockerImageOperations.cs
> +          throw new Exception($"Failed to create image {image.FullName}");
Something like

```csharp
if (!imageHasBeenCreated)
{
  throw new InvalidOperationException($"Docker image {image.FullName} has not been created.");
}
```

2022-07-04 06:16 UTC, michal-korniak commented on src/Testcontainers/Clients/DockerImageOperations.cs
> +        bool isImageCreated = await this.ExistsWithNameAsync(image.FullName, ct).ConfigureAwait(false);
changes

2022-07-04 06:17 UTC, michal-korniak commented on src/Testcontainers/Clients/DockerImageOperations.cs
> +          throw new Exception($"Failed to create image {image.FullName}");
changed

2022-07-04 16:35 UTC, HofmeisterAn approved these changes
I'll merge it together with the other pull requests. Thanks.

2022-07-05 17:33 UTC, closed without merging