DockerImageOperations.BuildAsync - Throwing meaningful exception if docker image name is not lower case
testcontainers/testcontainers-dotnet pull request #512
Opened 2022-07-15 12:43 UTC by michal-korniak

Currently this scenario isn't properly handled which leads to the exception with low level message that doesn't give any clues what went wrong.

![image](https://user-images.githubusercontent.com/16215158/179224345-e65478d9-040f-401d-af34-4bcb5da23878.png)

I wanted to add unit tests to this, but it will require more time than I can afford, The BuildAsync method invokes methods from static classes, so it will be necessary to create additional abstractions to make it mockable.

2022-07-15 13:04 UTC, HofmeisterAn requested changes
Can we add that as a guard methode to: https://github.com/testcontainers/testcontainers-dotnet/blob/39671c01d057567ae0ad505925236be27550982c/src/Testcontainers/Images/DockerImage.cs#L42? Then it's easier to test too.

2022-07-15 13:40 UTC, michal-korniak commented
Much easier :) I moved the logic to the class you mentioned and I added some tests to check if it work properly.

2022-07-16 06:15 UTC, HofmeisterAn commented
> easier to test too. What do th

Cool, thanks. I'll do the review and merge later that day 👏.

2022-07-16 17:22 UTC, HofmeisterAn approved these changes

2022-07-16 17:55 UTC, HofmeisterAn commented
I fixed the unit test, thanks (https://github.com/testcontainers/testcontainers-dotnet/commit/dcd1858046059478bb3cd1bca8acfb6a48d69854).

2022-07-16 17:55 UTC, closed without merging