feat(#540): Support for registry auth credentials from env var DOCKER_AUTH_CONFIG
testcontainers/testcontainers-dotnet pull request #550
Opened 2022-08-02 20:34 UTC by vova-lantsov-dev

2022-08-03 00:02 UTC, vova-lantsov-dev commented
@HofmeisterAn ubuntu pipeline got stuck?

2022-08-03 18:41 UTC, HofmeisterAn requested changes
Thanks for your pull request. I have two minor suggestions. I really like your `EnvironmentVariableScope` nice idea.

> @HofmeisterAn ubuntu pipeline got stuck?

Yep, since one of the last pull request the pipeline dose not run reliable anymore 😕. I am on it.

2022-08-03 18:41 UTC, HofmeisterAn commented on src/Testcontainers/Builders/EnvironmentVariableBase64Provider.cs
> +      var environmentVariableValue = Environment.GetEnvironmentVariable("DOCKER_AUTH_CONFIG");
Can we move this to `CustomConfiguration`? Something like `public JsonElement GetDockerAuthConfig()`? `EnvironmentConfiguration` and `PropertiesFileConfiguration` will be singeltons to access the configuration in the future.

2022-08-03 18:41 UTC, HofmeisterAn commented on src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs
> +                new Base64Provider(dockerConfigDocument, this.logger),
If you extend `CustomConfiguration` as suggested below, you can pass the `GetDockerAuthConfig` result to `Base64Provider`. I think you don't need `EnvironmentVariableBase64Provider` at all.

2022-08-06 20:36 UTC, vova-lantsov-dev commented
@HofmeisterAn I don't completely understand the purpose of these classes (`CustomConfiguration`, `EnvironmentConfiguration` and `PropertiesFileConfiguration`) in case of `DockerRegistryAuthenticationProvider` logic, but I made some changes, please review them and let me know if I misunderstood anything

2022-08-07 07:46 UTC, HofmeisterAn reviewed
> @HofmeisterAn I don't completely understand the purpose of these classes (`CustomConfiguration`, `EnvironmentConfiguration` and `PropertiesFileConfiguration`) in case of `DockerRegistryAuthenticationProvider` logic, but I made some changes, please review them and let me know if I misunderstood anything

I was thinking about something like this: [vova-lantsov-dev-feature/env-var-base64-auth](https://github.com/testcontainers/testcontainers-dotnet/compare/vova-lantsov-dev-feature/env-var-base64-auth?expand=1). I have not tested it yet, but what do you think?

- [ ] Add Docker auth config test to `CustomConfigurationTest`

2022-08-08 18:46 UTC, HofmeisterAn reviewed
If you have some time to test [vova-lantsov-dev-feature/env-var-base64-auth](https://github.com/testcontainers/testcontainers-dotnet/tree/vova-lantsov-dev-feature/env-var-base64-auth), I can merge your and my changes and close this PR.

2022-08-09 22:22 UTC, vova-lantsov-dev commented
I reviewed and applied your changes, but with small change:

![image](https://user-images.githubusercontent.com/45858087/183771853-a6d0ebab-c655-4ad8-bd00-c603afda69a9.png)

`GetDefaultDockerAuthConfig()` now returns nullable value because we want to check for default docker config even if `dockerConfigFile` doesn't exist (`else if` block)

2022-08-09 22:23 UTC, vova-lantsov-dev commented
I can test this on my local machine and CI server if you pack it into the NuGet

2022-08-10 19:30 UTC, HofmeisterAn approved these changes

2022-08-10 19:35 UTC, HofmeisterAn reviewed
Published in `2.2.0-beta.2835065501` (ced98a9db6c70c188b113938decc25d12d03e6fc), closes #540.

2022-08-10 21:22 UTC, vova-lantsov-dev commented
@HofmeisterAn I confirm that it works locally with `.docker` directory and on CI/CD server with `DOCKER_AUTH_CONFIG` env variable. I think we can merge this to develop and pack into release tag

2022-08-11 09:18 UTC, vova-lantsov-dev commented
By the way, it looks that I tested not the same code as this PR produces. That's why we have conflict

2022-08-11 09:20 UTC, vova-lantsov-dev commented
Oh, I see, you made some further changes. Do you want me to repeat them in my code, or you will just close the PR?

2022-08-11 13:25 UTC, HofmeisterAn commented
> Do you want me to repeat them in my code, or you will just close the PR?

No, not necessary. I merged and pushed all changes to develop already. You tested the right version. Thanks again.

2022-08-11 13:25 UTC, closed without merging

2022-08-26 09:56 UTC, vova-lantsov-dev commented
Hi @HofmeisterAn 
Please let me know when you plan to publish the release version containing this feature? It's quite strange to use the beta version of package in production environment :)

2022-08-26 19:21 UTC, HofmeisterAn commented
No ETA yet. I'd like to add the custom HTTP headers to the next version first.