Configuration providers provide current values
testcontainers/testcontainers-dotnet pull request #577
Opened 2022-09-07 11:28 UTC by vlaskal

Configuration providers provide current value from environment variables or setting file.
This is suggestion how to fix issue #576 to make test runnable nd independent on the order.

2022-09-07 11:47 UTC, vlaskal commented
This solution will work even for this test modification for TLS:
```csharp
[CollectionDefinition(nameof(DockerEndpointAuthenticationProviderTest), DisableParallelization = true)]
  [Collection(nameof(DockerEndpointAuthenticationProviderTest))]
  public sealed class DockerEndpointAuthenticationProviderTest
  {
    [Theory]
    [ClassData(typeof(AuthConfigTestData))]
    public void GetDockerClientConfiguration(IDockerEndpointAuthenticationConfiguration authConfig, Uri expectedDockerClientEndpoint)
    {
      using (var dockerClientConfiguration = authConfig.GetDockerClientConfiguration())
      {
        Assert.Equal(expectedDockerClientEndpoint, authConfig.Endpoint);
        Assert.Equal(expectedDockerClientEndpoint, dockerClientConfiguration.EndpointBaseUri);
      }
    }

    private sealed class AuthConfigTestData : List<object[]>
    {
      public AuthConfigTestData()
      {
        const string dockerHostVariableName = "DOCKER_HOST";
        const string dockerHost = "tcp://127.0.0.1:2375";
        const string dockerHostTls = "tcp://127.0.0.1:2376";

        var originalDockerHostvalue = Environment.GetEnvironmentVariable(dockerHostVariableName);

        Environment.SetEnvironmentVariable(dockerHostVariableName, dockerHostTls);
        this.Add(new object[] { new TlsEndpointAuthenticationProvider().GetAuthConfig(), new Uri(dockerHostTls) });

        Environment.SetEnvironmentVariable(dockerHostVariableName, dockerHost);
        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider().GetAuthConfig(), new Uri(dockerHost) });
        this.Add(new object[] { new NpipeEndpointAuthenticationProvider().GetAuthConfig(), new Uri("npipe://./pipe/docker_engine") });
        this.Add(new object[] { new UnixEndpointAuthenticationProvider().GetAuthConfig(), new Uri("unix:/var/run/docker.sock") });

        Environment.SetEnvironmentVariable(dockerHostVariableName, originalDockerHostvalue);
      }
    }
  }
```

2022-09-07 13:39 UTC, HofmeisterAn reviewed
I think all we need is DI. What do you think about:

```csharp
diff --git a/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs b/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
index f725eff..455c96c 100644
--- a/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
+++ b/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
@@ -1,31 +1,43 @@
 ﻿namespace DotNet.Testcontainers.Builders
 {
-  using System;
+  using System.Linq;
   using DotNet.Testcontainers.Configurations;
 
   /// <inheritdoc cref="IDockerRegistryAuthenticationProvider" />
   internal sealed class EnvironmentEndpointAuthenticationProvider : DockerEndpointAuthenticationProvider
   {
-    private readonly Uri dockerEngine;
+    private readonly ICustomConfiguration customConfiguration;
 
     /// <summary>
     /// Initializes a new instance of the <see cref="EnvironmentEndpointAuthenticationProvider" /> class.
     /// </summary>
     public EnvironmentEndpointAuthenticationProvider()
+      : this(PropertiesFileConfiguration.Instance, EnvironmentConfiguration.Instance)
     {
-      this.dockerEngine = PropertiesFileConfiguration.Instance.GetDockerHost() ?? EnvironmentConfiguration.Instance.GetDockerHost();
+    }
+
+    /// <summary>
+    /// Initializes a new instance of the <see cref="EnvironmentEndpointAuthenticationProvider" /> class.
+    /// </summary>
+    /// <param name="customConfigurations">A list of custom configurations.</param>
+    public EnvironmentEndpointAuthenticationProvider(params ICustomConfiguration[] customConfigurations)
+    {
+      this.customConfiguration = customConfigurations
+        .OrderByDescending(item => item.GetDockerHost() != null && item.GetDockerTls())
+        .ThenByDescending(item => item.GetDockerHost() != null)
+        .First();
     }
 
     /// <inheritdoc />
     public override bool IsApplicable()
     {
-      return this.dockerEngine != null;
+      return this.customConfiguration.GetDockerHost() != null;
     }
 
     /// <inheritdoc />
     public override IDockerEndpointAuthenticationConfiguration GetAuthConfig()
     {
-      return new DockerEndpointAuthenticationConfiguration(this.dockerEngine);
+      return new DockerEndpointAuthenticationConfiguration(this.customConfiguration.GetDockerHost());
     }
   }
 }
diff --git a/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs b/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
index 5f1fe66..d1c8963 100644
--- a/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
+++ b/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
@@ -26,11 +26,12 @@
       public AuthConfigTestData()
       {
         const string dockerHost = "tcp://127.0.0.1:2375";
-        Environment.SetEnvironmentVariable("DOCKER_HOST", dockerHost);
-        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider().GetAuthConfig(), new Uri(dockerHost) });
+        ICustomConfiguration dockerTlsDisabled = new PropertiesFileConfiguration("docker.host=" + dockerHost, "docker.tls=false");
+        ICustomConfiguration dockerTlsEnabled = new PropertiesFileConfiguration("docker.host=" + dockerHost, "docker.tls=true");
+        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider(dockerTlsDisabled).GetAuthConfig(), new Uri(dockerHost) });
+        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider(dockerTlsEnabled).GetAuthConfig(), new Uri(dockerHost) });
         this.Add(new object[] { new NpipeEndpointAuthenticationProvider().GetAuthConfig(), new Uri("npipe://./pipe/docker_engine") });
         this.Add(new object[] { new UnixEndpointAuthenticationProvider().GetAuthConfig(), new Uri("unix:/var/run/docker.sock") });
-        Environment.SetEnvironmentVariable("DOCKER_HOST", null);
       }
     }
   }
```

This will prioritize TLS configurations too.

2022-09-07 20:31 UTC, vlaskal commented
I am not sure but this bug is about environment configuration problem and not about TLS. I think mixing environment configuration with settings files does not make sense to me. Maybe I am blind., but I thin that tls should not be as argument for `EnvironmentEndpointAuthenticationProvider` which should provide that value. I do not see solution for current situation.

2022-09-08 04:47 UTC, HofmeisterAn commented
My example is poorly chosen - sorry. Forget about `GetDockerTls()`, etc. I meant to say that all you need is DI. The singleton makes the class difficult to test, DI solves that. My example above is showing the idea with different custom configurations.

An authentication provider depend on the custom configuration. Overload the constructor with `ICustomConfiguration`. The default constructor will fall back to the singleton instances. Your tests will use the overloaded constructor, specific with the custom configuration you need (very common pattern).

Overload the constructor with either `params ICustomConfiguration[] customConfigurations` or `ICustomConfiguration propertiesFileConfiguration, ICustomConfiguration environmentConfiguration`. For now, I personally prefer the first one, it is easier to set up in the tests.

2022-09-16 09:51 UTC, HofmeisterAn requested changes
I think making the class testable is the right approach, I suggest following fix:

```csharp
diff --git a/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs b/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
index f725eff..ee971f0 100644
--- a/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
+++ b/src/Testcontainers/Builders/EnvironmentEndpointAuthenticationProvider.cs
@@ -1,6 +1,7 @@
 ∩╗┐namespace DotNet.Testcontainers.Builders
 {
   using System;
+  using System.Linq;
   using DotNet.Testcontainers.Configurations;
 
   /// <inheritdoc cref="IDockerRegistryAuthenticationProvider" />
@@ -12,8 +13,17 @@
     /// Initializes a new instance of the <see cref="EnvironmentEndpointAuthenticationProvider" /> class.
     /// </summary>
     public EnvironmentEndpointAuthenticationProvider()
+      : this(PropertiesFileConfiguration.Instance, EnvironmentConfiguration.Instance)
     {
-      this.dockerEngine = PropertiesFileConfiguration.Instance.GetDockerHost() ?? EnvironmentConfiguration.Instance.GetDockerHost();
+    }
+
+    /// <summary>
+    /// Initializes a new instance of the <see cref="EnvironmentEndpointAuthenticationProvider" /> class.
+    /// </summary>
+    /// <param name="customConfigurations">A list of custom configurations.</param>
+    public EnvironmentEndpointAuthenticationProvider(params ICustomConfiguration[] customConfigurations)
+    {
+      this.dockerEngine = customConfigurations.Select(customConfiguration => customConfiguration.GetDockerHost()).FirstOrDefault(dockerHost => dockerHost != null);
     }
 
     /// <inheritdoc />
diff --git a/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs b/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
index 5f1fe66..aa05505 100644
--- a/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
+++ b/tests/Testcontainers.Tests/Unit/Configurations/DockerEndpointAuthenticationProviderTest.cs
@@ -26,11 +26,10 @@
       public AuthConfigTestData()
       {
         const string dockerHost = "tcp://127.0.0.1:2375";
-        Environment.SetEnvironmentVariable("DOCKER_HOST", dockerHost);
-        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider().GetAuthConfig(), new Uri(dockerHost) });
+        ICustomConfiguration dockerHostConfiguration = new PropertiesFileConfiguration(new[] { "docker.host=" + dockerHost });
+        this.Add(new object[] { new EnvironmentEndpointAuthenticationProvider(dockerHostConfiguration).GetAuthConfig(), new Uri(dockerHost) });
         this.Add(new object[] { new NpipeEndpointAuthenticationProvider().GetAuthConfig(), new Uri("npipe://./pipe/docker_engine") });
         this.Add(new object[] { new UnixEndpointAuthenticationProvider().GetAuthConfig(), new Uri("unix:/var/run/docker.sock") });
-        Environment.SetEnvironmentVariable("DOCKER_HOST", null);
       }
     }
   }
```

Would you like to update your pull request or should I do it?

2022-09-16 18:49 UTC, vlaskal commented
@HofmeisterAn Sory for late answer. I will update it.

2022-09-18 19:56 UTC, vlaskal commented
Fix was updated based on suggestion and covered by one mroe test.

2022-09-29 13:07 UTC, HofmeisterAn commented
f0f112bd53cc4c1ff8dcbb2001334a1b36a9f487, closes #576.

2022-09-29 13:07 UTC, closed without merging