add method to set a fixed container mac address
testcontainers/testcontainers-dotnet pull request #616
Opened 2022-10-15 06:00 UTC by seb1992

Add method 'WithMacAddress' to set a fixed mac address to a container in TestContainersBuilder. As background information to why I need this: I want to test software that requires a license key that is tied to the mac address.

2022-10-15 07:31 UTC, HofmeisterAn requested changes
Thanks for your pull request 🙏. I suggest to rename `macaddress` to `macAddress`. Can you please add a test to `TestcontainersContainerTest`?

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Builders/ITestcontainersBuilder.cs
> +    /// Sets the mac address of the Testcontainer.
```suggestion
    /// Sets the MAC address of the Testcontainer.
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Builders/ITestcontainersBuilder.cs
> +    /// <param name="macaddress">Testcontainers mac address.</param>
```suggestion
    /// <param name="macAddress">Testcontainers MAC address.</param>
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Builders/ITestcontainersBuilder.cs
> +    ITestcontainersBuilder<TDockerContainer> WithMacAddress(string macaddress);
```suggestion
    ITestcontainersBuilder<TDockerContainer> WithMacAddress(string macAddress);
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Configurations/Containers/ITestcontainersConfiguration.cs
> +    /// GEts the mac address.
```suggestion
    /// Gets the MAC address.
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Configurations/Containers/TestcontainersConfiguration.cs
> +    /// <param name="macaddress">The mac address.</param>
```suggestion
    /// <param name="macAddress">The MAC address.</param>
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Configurations/Containers/TestcontainersConfiguration.cs
> +      string macaddress = null,
```suggestion
      string macAddress = null,
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Configurations/Containers/TestcontainersConfiguration.cs
> +    public string MacAddress { get; }
```suggestion
    /// <inheritdoc />
    public string MacAddress { get; }
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Builders/TestcontainersBuilder.cs
> +    public ITestcontainersBuilder<TDockerContainer> WithMacAddress(string macaddress)
```suggestion
    public ITestcontainersBuilder<TDockerContainer> WithMacAddress(string macAddress)
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Builders/TestcontainersBuilder.cs
> +      return this.MergeNewConfiguration(new TestcontainersConfiguration(macaddress: macaddress));
```suggestion
      return this.MergeNewConfiguration(new TestcontainersConfiguration(macAddress: macAddress));
```

2022-10-15 07:31 UTC, HofmeisterAn commented on src/Testcontainers/Configurations/Containers/TestcontainersConfiguration.cs
> +      this.MacAddress = macaddress;
```suggestion
      this.MacAddress = macAddress;
```

2022-10-15 08:20 UTC, seb1992 commented
Thanks for the quick review! I executed the suggested renaming and added a test.

Viele Grüße aus dem Schwarzwald. ;)

2022-10-16 08:11 UTC, HofmeisterAn approved these changes
Thanks again for the contribution.

> Viele Grüße aus dem Schwarzwald. ;)

Grüße zurück 😀

2022-10-16 08:52 UTC, HofmeisterAn commented
f2cb532db6da73d0d79190369f202f75fb9717c7.

2022-10-16 08:52 UTC, closed without merging