Add Aws DynamoDB Module
testcontainers/testcontainers-dotnet pull request #768
Opened 2023-02-09 09:54 UTC by dominikus1993

## What does this PR do?
Add support for amazon DynamoDB testcontainer module.

## Why is it important?
I think that adding this testcontainer will be useful for developers who want to test the operation of aws dynamodb

## Related issues
- Any of issues are no releated

## How to test this PR
Running the new integration test will suffice.

2023-02-09 16:16 UTC, HofmeisterAn requested changes
Thank for your contribution again. I have a few suggestions for improvements.

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/DynamoDBBuilder.cs
> +public sealed class DynamoDBBuilder : ContainerBuilder<DynamoDBBuilder, DynamoDBContainer, DynamoDBConfiguration>
Can we rename `DynamoDB` to `DynamoDb` (files, classes, etc.)?

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/DynamoDBBuilder.cs
> +
```suggestion

```

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/DynamoDBBuilder.cs
> +            .WithWaitStrategy(Wait.ForUnixContainer().AddCustomWaitStrategy(new WaitUntil(DynamoDbPort)));
```suggestion
            .WithWaitStrategy(Wait.ForUnixContainer().UntilHttpRequestIsSucceeded(request => request.ForPath("/").ForPort(DynamoDbPort))
```

Then you can remove the `WaitUntil` implementation below.

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/DynamoDBContainer.cs
> +
```suggestion
```

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/DynamoDBContainer.cs
> +    public AmazonDynamoDBClient GetAmazonDynamoDBClient()
This is an ongoing topic. Until now, we do not include client dependencies in modules. Otherwise, we would force developers to use certain versions of client dependencies which may conflict with the version they require or would like to use.

The intension is nice, but can we remove it for now until we are certain how we would like to deal with it in the future?

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/Testcontainers.DynamoDB.csproj
> +</Project>
```suggestion
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2022.3.1"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src/Testcontainers/Testcontainers.csproj"/>
  </ItemGroup>
</Project>
```

2023-02-09 16:16 UTC, HofmeisterAn commented on src/Testcontainers.DynamoDB/Usings.cs
> +global using System.Threading.Tasks;
```suggestion
global using System;
global using System.Threading.Tasks;
global using Docker.DotNet.Models;
global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Configurations;
global using DotNet.Testcontainers.Containers;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Logging;
```

2023-02-09 16:16 UTC, HofmeisterAn commented on tests/Testcontainers.DynamoDB.Tests/Testcontainers.DynamoDB.Tests.csproj
> +</Project>
```suggestion
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1"/>
    <PackageReference Include="coverlet.msbuild" Version="3.2.0"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5"/>
    <PackageReference Include="xunit" Version="2.4.2"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src/Testcontainers.DynamoDB/Testcontainers.DynamoDB.csproj"/>
    <ProjectReference Include="$(SolutionDir)tests/Testcontainers.Commons/Testcontainers.Commons.csproj"/>
  </ItemGroup>
</Project>
```

You need to be careful with the `ProjectReference` path separator. `\` breaks on macOS or Linux.

2023-02-09 16:16 UTC, HofmeisterAn commented on tests/Testcontainers.DynamoDB.Tests/Usings.cs
> +global using Amazon.Runtime;
```suggestion
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Net;
global using System.Threading.Tasks;
global using Amazon.DynamoDBv2;
global using Amazon.DynamoDBv2.Model;
global using Amazon.Runtime;
global using DotNet.Testcontainers.Commons;
global using Xunit;
```

2023-02-09 16:19 UTC, dominikus1993 commented on src/Testcontainers.DynamoDB/DynamoDBBuilder.cs
> +public sealed class DynamoDBBuilder : ContainerBuilder<DynamoDBBuilder, DynamoDBContainer, DynamoDBConfiguration>
Yeah No problem i will do it tomorrow

2023-02-10 09:10 UTC, dominikus1993 commented on src/Testcontainers.DynamoDB/DynamoDBBuilder.cs
> +
fixed

2023-02-10 09:11 UTC, dominikus1993 commented on tests/Testcontainers.DynamoDB.Tests/Testcontainers.DynamoDB.Tests.csproj
> +</Project>
fixed

2023-02-10 09:11 UTC, dominikus1993 commented on tests/Testcontainers.DynamoDB.Tests/Usings.cs
> +global using Amazon.Runtime;
fixed

2023-02-10 09:11 UTC, dominikus1993 commented on src/Testcontainers.DynamoDB/DynamoDBContainer.cs
> +    public AmazonDynamoDBClient GetAmazonDynamoDBClient()
ok, fixed it

2023-02-10 09:11 UTC, dominikus1993 commented on src/Testcontainers.DynamoDB/Usings.cs
> +global using System.Threading.Tasks;
fixed

2023-02-10 09:12 UTC, dominikus1993 commented on src/Testcontainers.DynamoDB/DynamoDBContainer.cs
> +
fixed

2023-02-10 11:33 UTC, HofmeisterAn approved these changes

2023-02-10 11:35 UTC, merged