[feature] Testcontainers.Pulsar
testcontainers/testcontainers-dotnet pull request #818
Opened 2023-03-05 04:05 UTC by eaba

- [sdk net7.0] Testcontainers.Pulsar.Tests @HofmeisterAn. 
- SharpPulsar 2.11.0
- Akka.NET 1.5.0
- Apache Pulsar 2.11.0

2023-03-05 08:32 UTC, HofmeisterAn requested changes
Thanks for your PR. Your efforts are highly appreciated, most parts look good and merely require cosmetic changes.

However, before I can proceed with reviewing your PR, I have a few change requests that need to be addressed. Specifically, I need you to remove the static host port binding and remove any changes that are not relevant to this PR.

Once you make these updates, I will be happy to continue with the review process. Thank you again for your contribution, and I look forward to seeing the updated changes.

2023-03-05 08:32 UTC, HofmeisterAn commented on Testcontainers.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Testcontainers.Couchbase", "src\Testcontainers.Couchbase\Testcontainers.Couchbase.csproj", "{58E94721-2681-4D82-8D94-0B2F9DB0D575}"
Can we please keep the old Visual Studio project type GUID for now and update to the new GUID in a separate PR? I would like to keep the changes for the module to a minimum. Please remove the unnecessary changes from the SLN.

2023-03-05 08:32 UTC, HofmeisterAn commented on global.json
> +    "version": "7.*",
Please revert this. We stick to LTS versions.

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +namespace Testcontainers.Pulsar
```suggestion
namespace Testcontainers.Pulsar
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +    /// <inheritdoc />
```suggestion
    }

    /// <inheritdoc />
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +          .WithWaitStrategy(Wait.ForUnixContainer())
I think you need to add a proper wait strategy. Your wait strategy just waits until the container is running, but not until the service inside it is ready.

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +            return container.CopyFileAsync(StartupScriptFilePath, Encoding.Default.GetBytes(startupScript.ToString()), 493, ct: ct);
```suggestion
            return container.CopyFileAsync(StartupScriptFilePath, Encoding.Default.GetBytes(startupScript.ToString()), 493, ct: ct);
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarConfiguration.cs
> +namespace Testcontainers.Pulsar
```suggestion
namespace Testcontainers.Pulsar
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarConfiguration.cs
> +    /// <summary>
```suggestion
    }

    /// <summary>
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarContainer.cs
> +namespace Testcontainers.Pulsar
```suggestion
namespace Testcontainers.Pulsar
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/Testcontainers.Pulsar.csproj
> +</Project>
```suggestion
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2022.3.1"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src/Testcontainers/Testcontainers.csproj"/>
    </ItemGroup>
</Project>
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +    public ushort PulsarSQLPort = 8081;
```suggestion
    public const ushort PulsarPort = 6650;
    public const ushort PulsarAdminPort = 8080;
    public const ushort PulsarSQLPort = 8081;
```

2023-03-05 08:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +          .WithPortBinding(this.PulsarSQLPort, this.PulsarSQLPort)
```suggestion
          .WithPortBinding(PulsarPort, true)
          .WithPortBinding(PulsarAdminPort, true)
          .WithPortBinding(PulsarSQLPort, true)
```

We never bind static host ports, please use random assigned host ports instead. Your container can resolve the port with `GetMappedPublicPort(ushort)`, see:

- https://dotnet.testcontainers.org/api/best_practices/ (2. and 3.)
- https://dotnet.testcontainers.org/api/create_docker_container/#examples

2023-03-05 08:32 UTC, HofmeisterAn commented on tests/Testcontainers.Pulsar.Tests/.editorconfig
> +root = true
Please add this file to the src project too.

2023-03-05 19:26 UTC, eaba commented on global.json
> +    "version": "7.*",
`SharpPulsar` is `NET7.0` only

2023-03-05 19:28 UTC, eaba commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +          .WithWaitStrategy(Wait.ForUnixContainer())
I followed `Testcontainers.Kafka`

2023-03-06 09:32 UTC, HofmeisterAn commented on global.json
> +    "version": "7.*",
Why cannot we use the `DotPulsar`? It supports .NET Standard 2.0 and above. It should be enough to test the container configuration and does not require so many changes.

2023-03-06 09:32 UTC, HofmeisterAn commented on src/Testcontainers.Pulsar/PulsarBuilder.cs
> +          .WithWaitStrategy(Wait.ForUnixContainer())
Kafka waits for a log message, not just until the container is running:

https://github.com/testcontainers/testcontainers-dotnet/blob/ebedc9a5d23566c8353cff18c8320ffd2b6b9b58/src/Testcontainers.Kafka/KafkaBuilder.cs#L67

2023-03-06 15:59 UTC, closed without merging