Introduce JanusGraph module
testcontainers/testcontainers-dotnet pull request #837
Opened 2023-03-17 08:25 UTC by rngcntr

## What does this PR do?

This PR adds a module for the Graph Database [JanusGraph](https://janusgraph.org).
For the moment, only the most basic configuration of JanusGraph — the `inmemory` storage backend — is supported. 
Support for other backends can be added later. However, this simple configuration should be sufficient to for the majority of use cases.

## Why is it important?

JanusGraph is used by a variety of companies to build scalable graph database solutions. By providing a Testcontainers module, we lower the entry barrier for new developers to write meaningful tests.

## Follow-ups

- [ ] Wait for final 1.0.0 Release of JanusGraph
- [ ] Support different storage backends

2023-03-17 09:43 UTC, rngcntr commented
For some reason, the container is unable to start properly in the CI. I'll have to push a few commits to add some temporary code for debugging.

2023-03-22 09:44 UTC, HofmeisterAn requested changes
Thank you so much for submitting this pull request! I've reviewed your changes and overall, everything looks great. However, I have a small change request regarding the 3rd party client dependencies.

2023-03-22 09:44 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
> +        <PackageReference Include="JanusGraph.Net" Version="0.4.2" />
We do not recommend and include client dependencies in modules. Otherwise, developers will run into dependency clashes (forced to use specific versions, etc.). We favor configurations without dependencies. The intention is nice, but can we remove it?

2023-03-22 09:44 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +using System.Net.WebSockets;
Can we move these usings to the gloab usings file?

2023-03-22 12:38 UTC, rngcntr commented on src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
> +        <PackageReference Include="JanusGraph.Net" Version="0.4.2" />
I get your point. Would it make more sense to you to move such a dependency to the tests so that users can refer to the tests for usage examples?

2023-03-22 12:41 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
> +        <PackageReference Include="JanusGraph.Net" Version="0.4.2" />
Absolute, that's what we usually do too.

2023-03-22 13:03 UTC, rngcntr commented on src/Testcontainers.JanusGraph/Testcontainers.JanusGraph.csproj
> +        <PackageReference Include="JanusGraph.Net" Version="0.4.2" />
Alright then, fixed it!

2023-03-23 12:57 UTC, HofmeisterAn submitted a review, later dismissed

2023-03-23 13:50 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
`0.6.3` seems to require a different wait strategy, it never completes the readiness check.

2023-03-23 14:12 UTC, rngcntr commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
I will have a look at it tomorrow.

2023-03-24 08:28 UTC, rngcntr commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
It appears this is a previously unknown issue with JanusGraph 0.6.3: https://github.com/JanusGraph/janusgraph/issues/3681

Nothing serious, it's just the default log level that has changed. I'll get back to you once either
1) the issue with 0.6.3 is resolved, or
2) I have figured out an environment setting to manually set the log level, or
3) 1.0.0 is released

2023-08-14 20:03 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
The mentioned issue seems to be fixed. Do you know if there is an image we can use that works, so we can close this pull request?

2023-08-22 05:32 UTC, rngcntr commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
Sorry for the late response, I was on vacation. Let's see if the CI succeeds when using 0.6.4

2023-08-22 06:40 UTC, rngcntr commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
So it works with the latest pre-release, but the version that contains the fix is not yet publicly released.

2023-08-22 17:22 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
No, worries. Ok, thanks. Then let's wait until it's public available?

2023-11-14 20:33 UTC, HofmeisterAn commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
It looks like there is a `1.0.0` release?

2023-11-15 08:53 UTC, rngcntr commented on src/Testcontainers.JanusGraph/JanusGraphBuilder.cs
> +    public const string JanusGraphImage = "janusgraph/janusgraph:0.6.3";
Yes! Thanks for the heads-up. I updated the version, let's see if the pipeline succeeds.
If everything looks good, I will also rebase the branch and then we're good to go

2023-11-15 18:58 UTC, HofmeisterAn approved these changes

2023-11-15 18:58 UTC, merged