RabbitMQ testcontainer documentation with example
testcontainers/testcontainers-dotnet pull request #918
Opened 2023-06-11 20:04 UTC by AnnaErdi

documentation

## What does this PR do?

Adds module documentation page for RabbitMQ testcontainer

## Why is it important?

The PR is contributing with one module-specific documentation, which was not available before.

## Related issues

-

2023-06-12 07:40 UTC, HofmeisterAn requested changes
Thank you for submitting your pull request! I have a few small suggestions. What are your thoughts on them?

2023-06-12 07:40 UTC, HofmeisterAn commented on docs/modules/rabbitmq.md
> +}
```suggestion
using System.Text;
using System.Threading;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using Testcontainers.RabbitMq;
using Xunit;

public sealed class RabbitMqContainerTest : IAsyncLifetime
{
  private readonly RabbitMqContainer _rabbitMqContainer = new RabbitMqBuilder().Build();

  public Task InitializeAsync()
  {
    return _rabbitMqContainer.StartAsync();
  }

  public Task DisposeAsync()
  {
    return _rabbitMqContainer.DisposeAsync().AsTask();
  }

  [Fact]
  public void ConsumeMessageFromQueue()
  {
    const string queue = "hello";

    const string message = "Hello World!";

    string actualMessage = null;

    // Signal the completion of message reception.
    EventWaitHandle waitHandle = new ManualResetEvent(false);

    // Create and establish a connection.
    var connectionFactory = new ConnectionFactory();
    connectionFactory.Uri = new Uri(_rabbitMqContainer.GetConnectionString());
    using var connection = connectionFactory.CreateConnection();

    // Send a message to the channel.
    using var channel = connection.CreateModel();
    channel.QueueDeclare(queue, false, false, false, null);
    channel.BasicPublish(string.Empty, queue, null, Encoding.Default.GetBytes(message));

    // Consume a message from the channel.
    var consumer = new EventingBasicConsumer(channel);
    consumer.Received += (_, eventArgs) =>
    {
      actualMessage = Encoding.Default.GetString(eventArgs.Body.ToArray());
      waitHandle.Set();
    };

    channel.BasicConsume(queue, true, consumer);
    waitHandle.WaitOne(TimeSpan.FromSeconds(1));

    Assert.Equal(message, actualMessage);
  }
}
```

2023-06-12 07:40 UTC, HofmeisterAn commented on docs/modules/rabbitmq.md
> +Here is an example of a pre-configured RabbitMQ [module](https://www.nuget.org/packages/Testcontainers.RabbitMq;).
```suggestion
Here is an example of a pre-configured RabbitMQ [module](https://www.nuget.org/packages/Testcontainers.RabbitMq).
```

2023-06-12 07:40 UTC, HofmeisterAn commented on docs/modules/rabbitmq.md
> +Make sure to install the [RabbitMQ.Client](https://www.nuget.org/packages/RabbitMQ.Client) package to be able to connect to RabbitMQ.
Should we add the required dependencies (as copy and paste snippet) to the top of the example, e.g. something like:

~~~
```console title="Install the NuGet dependencies"
dotnet add package Testcontainers.RabbitMq
dotnet add package RabbitMQ.Client
```
~~~

and then

~~~
```csharp title="Run RabbitMQ test"
```
~~~

?

2023-06-12 20:11 UTC, AnnaErdi commented
Thank you for the suggestions, I modified it accordingly

2023-06-13 06:12 UTC, HofmeisterAn approved these changes

2023-06-13 06:38 UTC, merged

2023-06-13 06:38 UTC, HofmeisterAn commented
> Thank you for the suggestions, I modified it accordingly

Thanks for your contribution!